"""Add initial tables

Revision ID: 5fb251eb0e12
Revises: 706ffdc5b920
Create Date: 2026-08-25 14:56:30.559957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb251eb0e12'
down_revision: Union[str, Sequence[str], None] = '706ffdc5b920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message', sa.String(), nullable=False))
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'message')
    # ### end Alembic commands ###
