"""modify question_schema

Revision ID: 706ffdc5b920
Revises: 
Create Date: 2026-08-24 22:41:19.099460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '706ffdc5b920'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Define and create the Enum type in PostgreSQL first
    messagerole_enum = postgresql.ENUM('USER', 'ASSISTANT', name='messagerole')
    messagerole_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # 2. Alter column with postgresql_using
    op.alter_column(
        'messages', 
        'role',
        existing_type=sa.VARCHAR(length=50),
        type_=messagerole_enum,
        existing_nullable=False,
        postgresql_using='role::messagerole'  # <-- Added here for upgrade
    )
    
    op.add_column('questions', sa.Column('model_answer', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('user_answer', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('question', sa.String(), nullable=False))
    op.drop_column('questions', 'subject')
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('questions', 'question')
    op.drop_column('questions', 'user_answer')
    op.drop_column('questions', 'model_answer')
    
    # Revert Enum back to VARCHAR
    messagerole_enum = postgresql.ENUM('USER', 'ASSISTANT', name='messagerole')
    op.alter_column(
        'messages',
        'role',
        type_=sa.VARCHAR(length=50),
        existing_type=messagerole_enum,
        existing_nullable=False,
        postgresql_using='role::text'  # <-- Converts Enum back to plain text
    )
    
    # Drop the Enum type after altering the column
    messagerole_enum.drop(op.get_bind(), checkfirst=True)
                
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###